# Generated by Django 5.0.4 on 2024-05-17 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('course', models.CharField(choices=[('course', 'course')], max_length=100)),
                ('entry_scheme', models.CharField(choices=[('entry_scheme', 'entry_scheme')], max_length=50)),
                ('intake', models.CharField(choices=[('intake', 'intake')], max_length=50)),
                ('sponsorship', models.CharField(choices=[('sponsorship', 'sponsorship')], max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('residence', models.CharField(max_length=255)),
            ],
        ),
    ]
