# Generated by Django 5.0.3 on 2024-05-17 09:22

import assessmentapp.models
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50, validators=[assessmentapp.models.validate_letters, django.core.validators.MinLengthValidator(3)])),
                ('lname', models.CharField(max_length=50, validators=[assessmentapp.models.validate_letters, django.core.validators.MinLengthValidator(3)])),
                ('course', models.CharField(choices=[('Certificate in Health Science', 'Certificate in Health Science'), ('Certificate in Apllied Technology', 'Certificate in Applied Technology'), ('Bachelor of information technology', 'Bachelor of Information Technology'), ('Bachelors in Business Technology', 'Certificate in Health Science'), ('Master of Public Health', 'Master of Public Health')], max_length=200)),
                ('entryscheme', models.CharField(choices=[('A-Level certificate', 'A-Level certificate'), ('Adult/Mature Learning', 'Adult/Mature Learning'), ('Certificate', 'Certificate'), ('Diploma', 'Diploma'), ('Bachelors', 'Bachelors')], max_length=200)),
                ('intake', models.CharField(choices=[('January Intake', 'January Intake'), ('May Intake', 'May Intake'), ('August Intake', 'August Intake')], max_length=200)),
                ('sponsorship', models.CharField(choices=[('Private', 'Private'), ('Government', 'Government'), ('Bursary', 'Bursary')], max_length=200)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=200)),
                ('dob', models.DateField(default=django.utils.timezone.now)),
                ('residence', models.CharField(max_length=255, validators=[assessmentapp.models.validate_letters, django.core.validators.MinLengthValidator(2)])),
            ],
        ),
    ]
